import stateParks from '../data/stateParks.json'
import terraceParks from '../data/terraceParks.json'
import { scaleCoordinates } from './geo';

// lon, lat

// DSU campus is generated by translate-scale-translate'ing the real SD park
// coordinates around the campus center. Terrace Park anchors are hand-curated
// to keep them on walkable land (Covell Lake makes the formula approach put
// pins in the water), so they're used directly without scaling.
const DSU_REFERENCE_POINT = [-97.110789, 44.012222];
const DSU_SCALE_LONG = 0.00045;
const DSU_SCALE_LAT = 0.00066;

const testPark = {
    name: "Custer Test",
    cords: [-97.112994, 44.012224],
    recordingsCount: 1,
    sectionsCount: 1,
    scaledCoords: [-97.112994, 44.012224]
};

const currentLocationTestPark = {
    name: "Current Location Test",
    cords: [-96.741620, 43.552725],
    recordingsCount: 1,
    sectionsCount: 1,
    scaledCoords: [-96.741620, 43.552725]
};

const testParks = [testPark, currentLocationTestPark];

function dsuScaledPoints() {
    return stateParks.map(park => ({
        ...park,
        scaledCoords: scaleCoordinates(park.cords, DSU_REFERENCE_POINT, DSU_SCALE_LONG, DSU_SCALE_LAT),
    }));
}

function terraceScaledPoints() {
    return terraceParks.map(park => ({
        ...park,
        scaledCoords: park.cords,
    }));
}

export function getScaledPoints(variant = 'dsu') {
    return variant === 'terrace' ? terraceScaledPoints() : dsuScaledPoints();
}

const scaledPoints = getScaledPoints('dsu');

export { currentLocationTestPark, testPark, testParks, scaledPoints };

export default scaledPoints;
